website/models.py
from . import db
from flask_login import UserMixin
from sqlalchemy.sql import func 
# db.Model is a table essentially -> is the model of a table
#flask login has UserMixin which allows users to login and out easily
class User(db.Model,UserMixin):
    id=db.Column(db.Integer, primary_key=True)
    email=db.Column(db.String(150) ,unique=True)
    username=db.Column(db.String(150) ,unique=True)
    password = db.Column(db.String(150))
    date_created=db.Column(db.DateTime(timezone=True),default=func.now())
    posts = db.relationship('Post', backref='user',passive_deletes=True)
    logs=db.relationship('Log', backref='users',passive_deletes=True)

class Post(db.Model): 
    id=db.Column(db.Integer, primary_key=True)
    text=db.Column(db.Text, nullable=False)
    date_created=db.Column(db.DateTime(timezone=True),default=func.now())
    author=db.Column(db.Integer, db.ForeignKey('user.id',ondelete='CASCADE'),nullable=False)
    tracker_type = db.Column(db.String(150))
    

class Log(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    timestamp = db.Column(db.String(150))
    notes = db.Column(db.String(150))
    user = db.Column(db.Integer, db.ForeignKey('user.id'))
    added_date_time = db.Column(db.String(150))

website/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from os import path
from flask_login import LoginManager

db=SQLAlchemy()
DB_NAME="database.db"



def create_app():
    app=Flask(__name__)
    app.config['SECRET_KEY']="abcdefg"
    app.config['SQLALCHEMY_DATABASE_URI'] = f'sqlite:///{DB_NAME}'
    db.init_app(app)

    from .views import views
    from .auth import auth

    app.register_blueprint(views,url_prefix='/')
    app.register_blueprint(auth,url_prefix='/')

    from .models import User,Post
    
    create_database(app)
    login_manager=LoginManager()
    login_manager.login_view = "auth.login" 
    # if someone tries to access a page and if theyre not logged in they'll be redirected to auth.login
    login_manager.init_app(app)

    @login_manager.user_loader
    def load_user(id):
        return User.query.get(int(id))

    return app

def create_database(app):
    if not path.exists("website/"+ DB_NAME):
        db.create_all(app=app)
        print("database created!")

website/auth.py
from flask import Blueprint, render_template,redirect,url_for,request,flash
from . import db
from .models import User
from flask_login import login_user,logout_user,login_required, current_user
from werkzeug.security import generate_password_hash,check_password_hash

auth=Blueprint("auth",__name__)

@auth.route('/login',methods=['GET','POST'])
def login():
    if request.method == 'POST':
        email=request.form.get("email")
        password=request.form.get("password")

        user=User.query.filter_by(email=email).first()
        if user:
            if check_password_hash(user.password,password):
                flash("login successful",category='success')
                login_user(user,remember=True)
                return redirect(url_for('views.home'))
            else:
                flash("password incorrect",category='error')
        else:        
            flash("user does not exist",category='error')

    return render_template("login.html",user=current_user)

@auth.route('/sign-up',methods=['GET','POST'])
def signup():
    if request.method == 'POST':
        email=request.form.get("email")
        username=request.form.get("username")
        password1=request.form.get("password1")
        password2=request.form.get("password2")

        email_exists=User.query.filter_by(email=email).first()
        username_exists=User.query.filter_by(username=username).first()
        if email_exists:
            flash('Email is already in use', category='error')
        elif username_exists:    
            flash('Username is already in use', category='error')
        elif password1!=password2:
            flash('Passwords dont match', category='error')
        elif len(username) < 2: 
            flash('Username must be at least 2 characters', category='error')
        elif len(password1) < 6: 
            flash('password must be at least 6 characters', category='error')
        elif len(email) < 4: 
            flash('email must be at least 4 characters', category='error')              
        else: 
            new_user=User(email=email,username=username,password=generate_password_hash(password1,method='sha256'))
            db.session.add(new_user)
            db.session.commit()
            login_user(new_user,remember=True)
            flash('User created successfully', category='success')
            return redirect(url_for('views.home'))
    return render_template("signup.html",user=current_user)     


@auth.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for("views.home"))   

website/views.py
from flask import Blueprint,render_template,request,flash,redirect,url_for
from flask_login import login_required,current_user
from .models import Post,User,Log
from . import db
views=Blueprint("views",__name__)

@views.route('/')
@views.route('/home')
@login_required
def home():
    posts=Post.query.all()
    logs=Log.query.all()
    return render_template('home.html', user=current_user,posts=posts,logs=logs) 

@views.route('/create-post', methods=['GET','POST'])
@login_required
def create_post():
    if request.method=='POST':
        text=request.form.get('text')
        tracker_type = request.form.get('type')
        if not text:
            flash('post cannot be empty',category='error')
        else:
            post=Post(text=text,tracker_type=tracker_type,author=current_user.id)
            db.session.add(post)
            db.session.commit()
            flash('post successfully created',category='success')  
            return redirect(url_for('views.home'))

    return render_template('create_post.html', user=current_user)

@views.route('/profile')
def profile():
    return "<h1>Profile</h1>"  

@views.route("/delete-post/<id>")
@login_required
def delete_post(id):
    post = Post.query.filter_by(id=id).first()
    
    if not post:
        flash("Post does not exist.", category='error')
    elif current_user.id != post.id:
        flash('You do not have permission to delete this post.', category='error')
    else:
        db.session.delete(post)
        db.session.commit()
        flash('Post deleted.', category='success')

    return redirect(url_for('views.home'))

@views.route("/edit-post/<id>",methods=['GET','POST'])
@login_required
def edit_post(id):
    post = Post.query.filter_by(id=id).first()

    if not post:
        flash("Post does not exist.", category='error')
    elif current_user.id != post.id:
        flash('You do not have permission to edit this post.', category='error')
    else:
        try:
            if request.method == 'POST':
                text = request.form.get('text')
                tracker_type = request.form.get('type')
                post = Post.query.filter_by(id=id).first()
                post.text = text
                post.tracker_type = tracker_type
                db.session.commit()
                flash('Tracker Updated Successfully.', category='success')
                return redirect(url_for('views.home'))
        except Exception as e:
            print(e)
            flash('Something went wrong.', category='error')

    return render_template("edit_post.html", user=current_user, Post=post)


@views.route("/posts/<username>")
@login_required
def posts(username):
    user = User.query.filter_by(username=username).first()

    if not user:
        flash('No user with that username exists.', category='error')
        return redirect(url_for('views.home'))

    posts = Post.query.filter_by(author=user.id).all()
    return render_template("posts.html", user=current_user, posts=posts, username=username)

@views.route('/add-log-page/<id>', methods=['GET', 'POST'])
@login_required
def add_log(id):
    from .models import Post, Log
    this_tracker = Post.query.get(id)
    import datetime
    now = datetime.datetime.now()
    try:
        if request.method == 'POST':
            when = request.form.get('date')
            notes = request.form.get('notes')
            from . import db
            new_log = Log(timestamp=when, notes=notes , user=current_user.id,
                          added_date_time=now)
            db.session.add(new_log)
            db.session.commit()
            flash('New Log Added', category='success')
            return redirect(url_for('views.home'))
    except Exception as e:
        print(e)
        flash('Something went wrong.', category='error')
    return render_template("add_log_page.html", user=current_user, Post=this_tracker, now=now)

website/templates/add_log_page.html
{% extends 'base.html' %}
{% block title %}Add Log{% endblock %}
{% block content %}
<h2 align="left" class="text-black");"> {{ user.username }}'s Log</h1>

<form method="post">
    <h3 align="center"></h3>
    <div class="form-group">

        <h2>Log for post #{{Post.id}}</h2>

        <div align="center">

            <br>

             <label for="date">When: </label>
        <input
            type="datetime-local"
            class="form-control"
            id="date"
            name="date"
            style="width: 300px; border-radius: 15px; text-align: center"
            value="{{now}}"
            required
        />
        

            <label for="notes">Notes: </label>
        <textarea
            class="form-control"
            id="notes"
            name="notes"
            placeholder="Enter log notes"
            maxlength="200"
            style="width: 300px; border-radius: 15px; text-align: center"
            required
        ></textarea>


            <br>
            <button type="submit" class="btn btn-warning"><b> Add Log</b></button>

        </div>


    </div>
</form>

{% endblock %}

website/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- CSS only -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <title>{% block title %}{% endblock %}</title>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container-fluid">
          <button
            class="navbar-toggler"
            type="button"
            data-bs-toggle="collapse"
            data-bs-target="#navbar"
          >
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbar">
            <div class="navbar-nav">
              <a class="nav-item nav-link" href="/home">Home</a>
              {% if user.is_authenticated %}
              <a class="nav-item nav-link" href="/logout">Logout</a>
              {% else %}
              <a class="nav-item nav-link" href="/login">Login</a>
              <a class="nav-item nav-link" href="/sign-up">Sign Up</a>
              {% endif %}
            </div>
          </div>
        </div>
      </nav>
    {% with messages = get_flashed_messages(with_categories=True) %}
      {%if messages %}
        {% for category, message in messages %}
          {% if category == 'error' %}
          <div class="alert alert-danger alert-dismissible fade show" role="alert" >
          {{message}}
          <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
        </div>
        {% else %}
        <div class="alert alert-success alert-dismissible fade show" role="alert" >
          {{message}}
          <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
        </div>
        {% endif %}
        {%endfor %}
      {%endif%}
    {% endwith %}
    <div class="container">{% block content %}{% endblock %}</div>

<!-- JavaScript Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous">
</script>
</body>
</html>

website/templates/create_post.html
{% extends "base.html" %}
{% block title %}createPost{% endblock %}
{% block content %}

<h1 align="center">Create Post</h1>
<form method="POST">
    <textarea name="text" id="text" class="form-control"></textarea>
    <br />
    <label style="padding-top: 10px" for="type">Workout Type</label>
                        <select style="width: 300px;border-radius: 15px; text-align: center" id="type"  class="form-control"  name="type" required>
                            <option value="Cardio">Cardio</option>
                            <option value="Strength Training">Strength Training</option>
                            <option value="Functional Training">Functional Training</option>
                            <option value="MMA">MMA</option>


                        </select>
    <br />                    
    <div align="center">
        <button type="submit" class="btn btn-lg btn-primary">Post</button>
    </div>
</form>
<br />
<div align="center">
    <a href="/home"><button type="button" class="btn btn-lg btn-secondary">Back</button></a>
</div>
{% endblock %}

website/templates/edit_post.html
{% extends "base.html" %}
{% block title %}createPost{% endblock %}
{% block content %}

<h1 align="center">Edit Post</h1>
<form method="POST" >
    <textarea name="text" id="text" class="form-control"></textarea>
    <br />
    <label style="padding-top: 10px" for="type">Workout Type</label>
                        <select style="width: 300px;border-radius: 15px; text-align: center" id="type"  class="form-control"  name="type" required>
                            <option value="Cardio">Cardio</option>
                            <option value="Strength Training">Strength Training</option>
                            <option value="Functional Training">Functional Training</option>
                            <option value="MMA">MMA</option>


                        </select>
    <br />                    
    <div align="center">
        <button type="submit" class="btn btn-lg btn-primary">Confirm Edit</button>
    </div>
</form>
<br />
<div align="center">
    <a href="/home"><button type="button" class="btn btn-lg btn-secondary">Back</button></a>
</div>
{% endblock %}

website/templates/home.html
{% extends "post_div.html" %}
{% block title %}Home{% endblock %}


<!--  
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Home</title>
</head>
<body>
    <h1>Home</h1>
</body>
</html>
-->

website/templates/login.html
{% extends "base.html" %}
{% block title %}Login{% endblock %}
{% block content %}
<link rel="stylesheet" href="../static/login.css">
<div class="login-page">
    <div class="form">
      <form method="POST">
        <h1 class='heading'>Log in</h1>
        <label>Email</label>
        <input
          type="email"
          name="email"
          placeholder="Enter your email address"
          class="form-control"
          
        />
        <br />
        <label>Password</label>
        <input
          type="password"
          name="password"
          placeholder="Enter your password"
          class="form-control"
          
        />
        <br />
        <input class="submit-button" type="submit" value="Log in" />
        <div class="bottom-text">
          <p>Don&#x27;t have an account?</p><a href="/sign-up">Sign up</a>
        </div>
      </form>
    </div>
  </div>
{% endblock %}

website/templates/post_div.html
{% extends "base.html" %} {% block title %}Home{% endblock %} {% block content
    %}
    <h1 align="center">{% block header %}Trackers{% endblock %}</h1>
    <div id="posts">
      {% for post in posts %}
      <div class="card border-dark">
        <div class="card-header d-flex justify-content-between align-items-center">
          <a href="/posts/{{post.user.username}}">{{post.user.username}}</a>
          {% if user.id == post.author %}
          <div class="btn-group">
            <button
              type="button"
              class="btn btn-sm btn-danger dropdown-toggle"
              data-bs-toggle="dropdown"
            ></button>
            <ul class="dropdown-menu">
              <li>
                <a href="/delete-post/{{post.id}}" class="dropdown-item">Delete</a>
                <a href="/edit-post/{{post.id}}" class="dropdown-item">Edit</a>
              </li>
            </ul>
          </div>
          {% endif %}
        </div>
        <div class="card-body">
          <div class="card-text">{{post.text}}</div>
          <div class="card-text">{{post.tracker_type}}</div>
          <div><a href="{{ url_for('views.add_log', id=post.id) }}" class="btn" style="border-radius: 15px; font-size: 20px">✚</a></div>
          {%for log in logs %}
          {{log.notes}}
          {% endfor %}
        </div>
        <div class="card-footer text-muted">{{post.date_created}}</div>
      </div>
      <br/ > {% endfor %}
    </div>
    <!--  -->
    <!-- <div class="row" style="margin-top: 2.5%;">
        <div class="offset-md-2 col-md-4">
          <div class="card">
            <div class="card-header">
              <div class="float-left" style="font-size:1.5rem;">Recent Sessions:</div>
              <a class="btn btn-warning float-right text-white"><i class="fas fa-record-vinyl"></i> Record a session</a>
            </div>
            <div class="card-body">
      
            </div>
          </div>
        </div>

        <div class="col-md-4">
          <div class="card">
            <div class="card-header">
              <div class="float-left" style="font-size:1.5rem;">Workout trackers:</div>
              <a class="btn btn-success float-right text-white" href=""><i class="fas fa-plus-circle"></i> Create new tracker</a>
            </div>
            <div class="card-body">
      
            </div>
          </div>
        </div>
      </div> -->
    <!--  -->
    {% block footer %}
    <div align="center">
      <a href="/create-post"
        ><button type="button" class="btn btn-primary btn-lg">
          Create a Tracker
        </button></a
      >
    </div>



   
      

    {% endblock %} 
    {% endblock %}

website/templates/posts.html
{% extends "post_div.html" %} {% block title %}{{username}}'s Posts{% endblock
    %} {% block header %} {{username}}'s Trackers {% endblock %} {% block footer %}
    <div align="center">
      <a href="/home"
        ><button type="button" class="btn btn-primary btn-lg">Back</button></a
      >
    </div>
    {% endblock %}

website/templates/signup.html
{% extends "base.html" %}
{% block title %}Signup{% endblock %}
{% block content %}
<link rel="stylesheet" href="../static/register.css" />
<div class="login-page">
    <div class="form" >
      <form method="POST">
        <br><br>
        <h1 class="heading">Sign up</h1>
        <label for="username">Username</label>
        <input
          type="text"
          name="username"
          placeholder="Enter your username..."
          required=""
          value=""
        />
        <br />
        <label for="email">Email</label>
        <input
          type="email"
          name="email"
          placeholder="Enter your email..."
          required=""
          value=""
        />
        <br />
        <label for="password1">Password</label>
        <input
          type="password"
          name="password1"
          id="password1"
          placeholder="Create a password..."
          required=""
          value=""
          class="form-control"
        />
        
        <label for="password2">Confirm password</label>
        <input
          type="password"
          name="password2"
          id="password2"
          placeholder="Confirm your password..."
          required=""
          value=""
          class="form-control"
        />
        <br />
        <input class="submit-button" type="submit" value="Sign up" />
        <div class="bottom-text">
          <p>Already have an account?</p>
          <a class="link" href="/login">Log In</a>
        </div>
      </form>
    </div>
  </div>
{% endblock %}